#!/usr/bin/env bash

# Adapted from https://orrsella.com/2013/08/10/git-using-different-user-emails-for-different-repositories/

# Config
name="Tim Cheung"
personal_email="tim@cheung.io"

work_git_remote_url_partial="faceit"
work_email="t.cheung@faceit.com"

setIdentity() {
    local current_email local_email

    current_email="$(git config --get --local user.email)"

    local_email=("$@")

    if [[ "${current_email}" == "${local_email}" ]]; then
        printf "\nUsing Git as: %s <%s>\n\n" "${name}" "${current_email}"
    else
        printf "\nUsing Git as: %s <%s>\n" "${name}" "${local_email}"
        git config --local user.email "${local_email}"
    fi

    return 0
}

current_remote_url="$(git config --get --local remote.origin.url)"

# Disable case sensitivity for regex matching
shopt -s nocasematch

if [[ "$current_remote_url" =~ $work_git_remote_url_partial ]]; then
    setIdentity "${work_email}"
    exit 0
else
    setIdentity "${personal_email}"
    exit 0
fi

exit 0
